export const product = Object.freeze({
  id: "northstar-cloud",
  name: "Northstar Cloud",
  release: "Enterprise candidate · 2026.09",
  question: "Can we safely promise SAML SSO to Business customers?",
  inspectedAt: "2026-09-03T09:12:00Z",
});

export const sourceKinds = Object.freeze({
  MARKETING: { label: "Marketing", authority: 20 },
  PRICING: { label: "Pricing", authority: 35 },
  DOCS: { label: "Docs", authority: 55 },
  CONTRACT: { label: "Contract", authority: 95 },
  REPO: { label: "Repository", authority: 90 },
  RUNTIME: { label: "Runtime", authority: 100 },
});

export const claims = Object.freeze([
  {
    id: "sso-plan",
    title: "SAML SSO availability",
    category: "Entitlement",
    customerPromise: "Business includes SAML SSO",
    decision: "Enterprise sales gate",
    canonicalText: {
      enterprise: "SAML SSO is available on the Enterprise plan.",
    },
  },
  {
    id: "retention-days",
    title: "Default data retention",
    category: "Compliance",
    customerPromise: "Customer data is deleted after 30 days",
    decision: "DPA review",
    canonicalText: {
      "90": "Customer data is retained for 90 days by default.",
    },
  },
  {
    id: "eu-residency",
    title: "EU data residency",
    category: "Infrastructure",
    customerPromise: "EU residency is available on every paid plan",
    decision: "Procurement review",
    canonicalText: {
      enterprise: "EU data residency is available on the Enterprise plan.",
    },
  },
  {
    id: "audit-log-days",
    title: "Audit log history",
    category: "Security",
    customerPromise: "Business stores 365 days of audit history",
    decision: "Security questionnaire",
    canonicalText: {
      "90": "Business stores 90 days of audit history; Enterprise stores 365 days.",
    },
  },
  {
    id: "encryption-at-rest",
    title: "Encryption at rest",
    category: "Security",
    customerPromise: "Stored data uses AES-256 encryption",
    decision: "Trust review",
    canonicalText: {
      "aes-256": "Stored customer data is encrypted with AES-256.",
    },
  },
  {
    id: "scim-provisioning",
    title: "SCIM provisioning",
    category: "Identity",
    customerPromise: "SCIM provisioning is available",
    decision: "Enterprise sales gate",
    canonicalText: {},
  },
]);

export const evidence = Object.freeze([
  {
    id: "marketing-sso",
    claimId: "sso-plan",
    sourceKind: "MARKETING",
    sourceLabel: "Enterprise landing",
    locator: "/enterprise#identity",
    value: "business",
    displayValue: "Business + Enterprise",
    statement: "SAML SSO is included from Business.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "pricing-sso",
    claimId: "sso-plan",
    sourceKind: "PRICING",
    sourceLabel: "Pricing matrix",
    locator: "/pricing#business",
    value: "business",
    displayValue: "Business",
    statement: "SAML single sign-on — Included",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "docs-sso",
    claimId: "sso-plan",
    sourceKind: "DOCS",
    sourceLabel: "Identity guide",
    locator: "/docs/saml-sso",
    value: "enterprise",
    displayValue: "Enterprise",
    statement: "SAML SSO requires an Enterprise workspace.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "repo-sso",
    claimId: "sso-plan",
    sourceKind: "REPO",
    sourceLabel: "Entitlement policy",
    locator: "config/entitlements.ts:41",
    value: "enterprise",
    displayValue: "Enterprise",
    statement: "samlSso: { minPlan: 'enterprise' }",
    provenance: "DERIVED_DETERMINISTIC",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },
  {
    id: "runtime-sso",
    claimId: "sso-plan",
    sourceKind: "RUNTIME",
    sourceLabel: "Business tenant trace",
    locator: "trace/tenant-biz-0142",
    value: "enterprise",
    displayValue: "Enterprise required",
    statement: "403 PLAN_UPGRADE_REQUIRED when enabling SAML.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },

  {
    id: "security-retention",
    claimId: "retention-days",
    sourceKind: "MARKETING",
    sourceLabel: "Security page",
    locator: "/security#retention",
    value: "30",
    displayValue: "30 days",
    statement: "Customer data is automatically deleted after 30 days.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "dpa-retention",
    claimId: "retention-days",
    sourceKind: "CONTRACT",
    sourceLabel: "Standard DPA",
    locator: "DPA §7.2",
    value: "90",
    displayValue: "90 days",
    statement: "Default retention period: 90 calendar days.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: false,
  },
  {
    id: "repo-retention",
    claimId: "retention-days",
    sourceKind: "REPO",
    sourceLabel: "Retention worker",
    locator: "jobs/retention.ts:18",
    value: "90",
    displayValue: "90 days",
    statement: "DEFAULT_RETENTION_DAYS = 90",
    provenance: "DERIVED_DETERMINISTIC",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },
  {
    id: "runtime-retention",
    claimId: "retention-days",
    sourceKind: "RUNTIME",
    sourceLabel: "Policy snapshot",
    locator: "runtime/policy-2026-09-03",
    value: "90",
    displayValue: "90 days",
    statement: "purge_after_days: 90",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },

  {
    id: "trust-eu",
    claimId: "eu-residency",
    sourceKind: "MARKETING",
    sourceLabel: "Trust center",
    locator: "/trust/data-residency",
    value: "all_paid",
    displayValue: "All paid plans",
    statement: "Choose EU data residency on any paid plan.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "repo-eu",
    claimId: "eu-residency",
    sourceKind: "REPO",
    sourceLabel: "Region policy",
    locator: "config/regions.ts:27",
    value: "enterprise",
    displayValue: "Enterprise",
    statement: "euWest1: { minPlan: 'enterprise' }",
    provenance: "DERIVED_DETERMINISTIC",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },
  {
    id: "runtime-eu",
    claimId: "eu-residency",
    sourceKind: "RUNTIME",
    sourceLabel: "Business region selector",
    locator: "trace/region-selector-biz",
    value: "enterprise",
    displayValue: "Enterprise required",
    statement: "EU region disabled; upgrade_required=true.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },

  {
    id: "pricing-audit",
    claimId: "audit-log-days",
    sourceKind: "PRICING",
    sourceLabel: "Business plan card",
    locator: "/pricing#business-audit",
    value: "365",
    displayValue: "365 days",
    statement: "365-day audit history",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "docs-audit",
    claimId: "audit-log-days",
    sourceKind: "DOCS",
    sourceLabel: "Audit log guide",
    locator: "/docs/audit-log#retention",
    value: "90",
    displayValue: "90 days",
    statement: "Business workspaces retain audit events for 90 days.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "runtime-audit",
    claimId: "audit-log-days",
    sourceKind: "RUNTIME",
    sourceLabel: "Business audit export",
    locator: "trace/audit-biz-90d",
    value: "90",
    displayValue: "90 days",
    statement: "oldest_available_event_days: 90",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },

  {
    id: "trust-encryption",
    claimId: "encryption-at-rest",
    sourceKind: "MARKETING",
    sourceLabel: "Trust center",
    locator: "/trust/encryption",
    value: "aes-256",
    displayValue: "AES-256",
    statement: "Customer data is encrypted at rest with AES-256.",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "repo-encryption",
    claimId: "encryption-at-rest",
    sourceKind: "REPO",
    sourceLabel: "Storage policy",
    locator: "infra/storage.tf:73",
    value: "aes-256",
    displayValue: "AES-256",
    statement: "sse_algorithm = 'AES256'",
    provenance: "DERIVED_DETERMINISTIC",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },
  {
    id: "runtime-encryption",
    claimId: "encryption-at-rest",
    sourceKind: "RUNTIME",
    sourceLabel: "Bucket configuration",
    locator: "runtime/storage-policy",
    value: "aes-256",
    displayValue: "AES-256",
    statement: "ServerSideEncryption: AES256",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: false,
    mutable: false,
  },

  {
    id: "pricing-scim",
    claimId: "scim-provisioning",
    sourceKind: "PRICING",
    sourceLabel: "Enterprise matrix",
    locator: "/pricing#scim",
    value: "available",
    displayValue: "Available",
    statement: "SCIM provisioning — Included",
    provenance: "OBSERVED",
    confidence: 1,
    customerFacing: true,
    mutable: true,
  },
  {
    id: "repo-scim-proposal",
    claimId: "scim-provisioning",
    sourceKind: "REPO",
    sourceLabel: "Route proposal",
    locator: "routes/scim.proposal.ts",
    value: "planned",
    displayValue: "Planned only",
    statement: "Proposed route exists; no executable handler is bound.",
    provenance: "MODEL_PROPOSED",
    confidence: 0.62,
    customerFacing: false,
    mutable: false,
  },
]);
